services:
#    doctissimo_blog.example:
#        class: Doctissimo\BlogBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]


  Doctissimo\APIBundle\Controller\:
          resource: '../../Controller'
          public: true
          arguments: ['doctissimo.apiManager']